# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  amplify = {
    pname = "amplify";
    version = "8b5d433163af10de1f1464055d62f04676cb3daf";
    src = fetchFromGitHub {
      owner = "aws-amplify";
      repo = "amplify-cli";
      rev = "8b5d433163af10de1f1464055d62f04676cb3daf";
      fetchSubmodules = false;
      sha256 = "sha256-C9XVYC2mwd8ttTFLs1mpFtPJ79N6X4Isf4PDsowbsDE=";
    };
    npmDepsHash = "sha256-2yXQgaRBjJnotz45bgx3DZ19aoQDFMxK+8CKyrTA7Qs=";
    date = "2023-09-15";
  };
  browsh = {
    pname = "browsh";
    version = "d32ae0ba5a1df266b96772fcd0b62ab8a76429ac";
    src = fetchFromGitHub {
      owner = "browsh-org";
      repo = "browsh";
      rev = "d32ae0ba5a1df266b96772fcd0b62ab8a76429ac";
      fetchSubmodules = false;
      sha256 = "sha256-LUHLaIW6aFa9yFJ+yqlkZtTk5LzN7r6xzHJKXWC2JnA=";
    };
    vendorHash = "sha256-eCvV3UuM/JtCgMqvwvqWF3bpOmPSos5Pfhu6ETaS58c=";
    date = "2023-02-02";
  };
  cmdg = {
    pname = "cmdg";
    version = "1c2fe5b72affaf19ff47033b0dfe744c37b49632";
    src = fetchFromGitHub {
      owner = "yuzukicat";
      repo = "cmdg";
      rev = "1c2fe5b72affaf19ff47033b0dfe744c37b49632";
      fetchSubmodules = false;
      sha256 = "sha256-oX5K7un9+LJQ9G+dNj4giIjq8BPBhzB5bAj+1ceS7nE=";
    };
    vendorHash = "sha256-p7p1GdwL+VqP7wHEmYwhc/CYKgMUFt7OYigWNGkJ2n8=";
    date = "2023-05-23";
  };
  colors = {
    pname = "colors";
    version = "94d8b2be62657e96488038b0e547e3009ed87d40";
    src = fetchurl {
      url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/94d8b2be62657e96488038b0e547e3009ed87d40/colors.py";
      sha256 = "sha256-l/RTPZp2v7Y4ffJRT5Fy5Z3TDB4dvWfE7wqMbquXdJA=";
    };
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v2.5.0-homebrew";
    src = fetchFromGitHub {
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v2.5.0-homebrew";
      fetchSubmodules = false;
      sha256 = "sha256-TiXTRgbwElTptx5QhmgIfd8pirWTv5EHgO5RxYWeTtU=";
    };
    vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=";
  };
  eml2md = {
    pname = "eml2md";
    version = "ca831e1e3661c51d4918344c4a448fa9b1da2144";
    src = fetchFromGitHub {
      owner = "elda27";
      repo = "eml2md";
      rev = "ca831e1e3661c51d4918344c4a448fa9b1da2144";
      fetchSubmodules = false;
      sha256 = "sha256-jNASJG7SRVZ4AYPkNBmqVn3x0tQQTmMFtpC5mck2WXk=";
    };
    date = "2022-11-29";
  };
  gopls = {
    pname = "gopls";
    version = "d2b79cdec8ff8fdd6466aec7776d7a834f3d885e";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "d2b79cdec8ff8fdd6466aec7776d7a834f3d885e";
      fetchSubmodules = false;
      sha256 = "sha256-8DJ6bYmp7qHlfUbmq4Q6oIBCnln0Xa22JBoyJ0mqYuw=";
    };
    vendorSha256 = "sha256-vTGyEq65crhius8EzuaBSgUrUc3e7P1X7v76qaYjXus=";
    date = "2023-09-18";
  };
  gotools = {
    pname = "gotools";
    version = "d2b79cdec8ff8fdd6466aec7776d7a834f3d885e";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "d2b79cdec8ff8fdd6466aec7776d7a834f3d885e";
      fetchSubmodules = false;
      sha256 = "sha256-8DJ6bYmp7qHlfUbmq4Q6oIBCnln0Xa22JBoyJ0mqYuw=";
    };
    vendorSha256 = "sha256-vTGyEq65crhius8EzuaBSgUrUc3e7P1X7v76qaYjXus=";
    date = "2023-09-18";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "e37e962d108889fbba93c926788766f73aa54e6a";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "e37e962d108889fbba93c926788766f73aa54e6a";
      fetchSubmodules = false;
      sha256 = "sha256-1NxJgaEfYX7dsOx75zmMwsXyvSEftA44auwKtcOVE5k=";
    };
    date = "2023-09-18";
  };
  mind-wave = {
    pname = "mind-wave";
    version = "b787803ff745dde28727c10833b397d846fc1f7f";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "mind-wave";
      rev = "b787803ff745dde28727c10833b397d846fc1f7f";
      fetchSubmodules = false;
      sha256 = "sha256-Uh3YcGQAFvxQjdvHQeZqy9NXFaQwGhkhFJuOn4CWG/k=";
    };
    date = "2023-09-15";
  };
  ohmyzsh-theme-passion = {
    pname = "ohmyzsh-theme-passion";
    version = "1d96f9984d581bbf6b64b940599786a9c91e2ad6";
    src = fetchFromGitHub {
      owner = "ChesterYue";
      repo = "ohmyzsh-theme-passion";
      rev = "1d96f9984d581bbf6b64b940599786a9c91e2ad6";
      fetchSubmodules = false;
      sha256 = "sha256-9mxHmMeA/tNO0axc8cQD1MzWsG0GIJc8a57MXKycZf4=";
    };
    date = "2023-05-19";
  };
  whisper-cpp = {
    pname = "whisper-cpp";
    version = "903c9579b86658798035cc9a3e358b355eb72a43";
    src = fetchFromGitHub {
      owner = "ggerganov";
      repo = "whisper.cpp";
      rev = "903c9579b86658798035cc9a3e358b355eb72a43";
      fetchSubmodules = false;
      sha256 = "sha256-nRFZRGj/esKVg4oGl3oohpkeQpHvxzCndQteEOPjjms=";
    };
    date = "2023-09-18";
  };
  xpi = {
    pname = "xpi";
    version = "1.8.2";
    src = fetchurl {
      url = "https://github.com/browsh-org/browsh/releases/download/v1.8.2/browsh-1.8.2.xpi";
      sha256 = "sha256-04rLyQt8co3Z7UJnDJmj++E4n7of0Zh1jQ90Bfwnx5A=";
    };
  };
}
