# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  browsh = {
    pname = "browsh";
    version = "d32ae0ba5a1df266b96772fcd0b62ab8a76429ac";
    src = fetchFromGitHub {
      owner = "browsh-org";
      repo = "browsh";
      rev = "d32ae0ba5a1df266b96772fcd0b62ab8a76429ac";
      fetchSubmodules = false;
      sha256 = "sha256-LUHLaIW6aFa9yFJ+yqlkZtTk5LzN7r6xzHJKXWC2JnA=";
    };
    vendorHash = "sha256-eCvV3UuM/JtCgMqvwvqWF3bpOmPSos5Pfhu6ETaS58c=";
    date = "2023-02-02";
  };
  cmdg = {
    pname = "cmdg";
    version = "1c2fe5b72affaf19ff47033b0dfe744c37b49632";
    src = fetchFromGitHub {
      owner = "yuzukicat";
      repo = "cmdg";
      rev = "1c2fe5b72affaf19ff47033b0dfe744c37b49632";
      fetchSubmodules = false;
      sha256 = "sha256-oX5K7un9+LJQ9G+dNj4giIjq8BPBhzB5bAj+1ceS7nE=";
    };
    vendorHash = "sha256-p7p1GdwL+VqP7wHEmYwhc/CYKgMUFt7OYigWNGkJ2n8=";
    date = "2023-05-23";
  };
  colors = {
    pname = "colors";
    version = "94d8b2be62657e96488038b0e547e3009ed87d40";
    src = fetchurl {
      url = "https://gist.githubusercontent.com/lilydjwg/fdeaf79e921c2f413f44b6f613f6ad53/raw/94d8b2be62657e96488038b0e547e3009ed87d40/colors.py";
      sha256 = "sha256-l/RTPZp2v7Y4ffJRT5Fy5Z3TDB4dvWfE7wqMbquXdJA=";
    };
  };
  double-entry-generator = {
    pname = "double-entry-generator";
    version = "v2.4.0";
    src = fetchFromGitHub {
      owner = "deb-sig";
      repo = "double-entry-generator";
      rev = "v2.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-XJsectuh2yO4t3nWi0aoBoNNf4AzxXtTmR/e6wrMzKk=";
    };
    vendorHash = "sha256-Xedva9oGteOnv3rP4Wo3sOHIPyuy2TYwkZV2BAuxY4M=";
  };
  eml2md = {
    pname = "eml2md";
    version = "ca831e1e3661c51d4918344c4a448fa9b1da2144";
    src = fetchFromGitHub {
      owner = "elda27";
      repo = "eml2md";
      rev = "ca831e1e3661c51d4918344c4a448fa9b1da2144";
      fetchSubmodules = false;
      sha256 = "sha256-jNASJG7SRVZ4AYPkNBmqVn3x0tQQTmMFtpC5mck2WXk=";
    };
    date = "2022-11-29";
  };
  gopls = {
    pname = "gopls";
    version = "82861e0385a62eddb77541a9ebb0cc9fd9a53389";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "82861e0385a62eddb77541a9ebb0cc9fd9a53389";
      fetchSubmodules = false;
      sha256 = "sha256-ghzv4cgXfKFJ+CGOGLdxaAaiVt5gfnXKhTwzHWkgNno=";
    };
    vendorSha256 = "sha256-xSbL2bCPFvuYKnuvwvzw4bvMjIVLZd4vJbi/FacpSCg=";
    date = "2023-07-28";
  };
  gotools = {
    pname = "gotools";
    version = "82861e0385a62eddb77541a9ebb0cc9fd9a53389";
    src = fetchFromGitHub {
      owner = "golang";
      repo = "tools";
      rev = "82861e0385a62eddb77541a9ebb0cc9fd9a53389";
      fetchSubmodules = false;
      sha256 = "sha256-ghzv4cgXfKFJ+CGOGLdxaAaiVt5gfnXKhTwzHWkgNno=";
    };
    vendorSha256 = "sha256-Nbpd4nNYfCTEw1trMXxTVZwSZ5CbUv0hAAi+0eDJLWU=";
    date = "2023-07-28";
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "7b56642135ef7b882f2b514ef88042af0e5a9274";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "lsp-bridge";
      rev = "7b56642135ef7b882f2b514ef88042af0e5a9274";
      fetchSubmodules = false;
      sha256 = "sha256-HzIar35DweTv9L3BpbhLlEAEr17kj7a+b9z8rbwxbYE=";
    };
    date = "2023-07-28";
  };
  mind-wave = {
    pname = "mind-wave";
    version = "994618abcd2c6a09af49b486d270ad4fd2d5b4a4";
    src = fetchFromGitHub {
      owner = "manateelazycat";
      repo = "mind-wave";
      rev = "994618abcd2c6a09af49b486d270ad4fd2d5b4a4";
      fetchSubmodules = false;
      sha256 = "sha256-IRT+ct8X2W/iS4+aIoibwR0br5FHWBDYCeNP8pGrpJs=";
    };
    date = "2023-07-24";
  };
  ohmyzsh-theme-passion = {
    pname = "ohmyzsh-theme-passion";
    version = "1d96f9984d581bbf6b64b940599786a9c91e2ad6";
    src = fetchFromGitHub {
      owner = "ChesterYue";
      repo = "ohmyzsh-theme-passion";
      rev = "1d96f9984d581bbf6b64b940599786a9c91e2ad6";
      fetchSubmodules = false;
      sha256 = "sha256-9mxHmMeA/tNO0axc8cQD1MzWsG0GIJc8a57MXKycZf4=";
    };
    date = "2023-05-19";
  };
  whisper-cpp = {
    pname = "whisper-cpp";
    version = "a792c4079ce61358134da4c9bc589c15a03b04ad";
    src = fetchFromGitHub {
      owner = "ggerganov";
      repo = "whisper.cpp";
      rev = "a792c4079ce61358134da4c9bc589c15a03b04ad";
      fetchSubmodules = false;
      sha256 = "sha256-3BePMZJ8FAZwqlPeUpG251Mdq+iaJWZvTJsi6eBtcyQ=";
    };
    date = "2023-07-26";
  };
  xpi = {
    pname = "xpi";
    version = "1.8.2";
    src = fetchurl {
      url = "https://github.com/browsh-org/browsh/releases/download/v1.8.2/browsh-1.8.2.xpi";
      sha256 = "sha256-04rLyQt8co3Z7UJnDJmj++E4n7of0Zh1jQ90Bfwnx5A=";
    };
  };
}
